version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: chapter-10-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./storage-db:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=chapter-10
        - MYSQL_USER=chapter-10
        - MYSQL_PASSWORD=123456
      ports:
        - "8083:3306"

    webserver:
      image: nginx:alpine
      container_name: chapter-10-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"

    php-fpm:
      build: docker/php-fpm
      container_name: chapter-10-php-fpm
      working_dir: /application
      volumes:
        - ./Server:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    
    appserver:
      image: 'angular-laravel-book'
      container_name: chapter-10-appserver
      # Build the image if don't exist
      build: './Client'
      ports:
          - 3000:81